version: '3.8'

services:
  nextjs-app-alfurqon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app-alfurqon
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://neondb_owner:npg_yo2PTxLukc1s@ep-lingering-dew-axy5bekt.c-4.us-east-2.aws.neon.tech/website_alfurqon?sslmode=require
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true